[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$ExpectedCommit,
    [Parameter(Mandatory)][string]$SbomPath,
    [string]$StageQualifier = '',
    [switch]$SkipSpaceCheck
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'Build.Common.ps1')
$build = Initialize-AStockBuildEnvironment -SkipSpaceCheck:$SkipSpaceCheck
$repository = $build.RepositoryRoot
$commit = (& git -C $repository rev-parse HEAD).Trim()
if ($LASTEXITCODE -ne 0 -or $commit -ne $ExpectedCommit -or $commit -notmatch '^[a-f0-9]{40}$') {
    throw 'Unsigned release staging is not bound to the expected immutable commit.'
}

$artifactRoot = [System.IO.Path]::GetFullPath($build.Paths.Artifacts)
$sbom = [System.IO.Path]::GetFullPath($SbomPath)
$artifactPrefix = $artifactRoot.TrimEnd('\') + '\'
if (-not $sbom.StartsWith($artifactPrefix, [StringComparison]::OrdinalIgnoreCase) -or
    -not (Test-Path -LiteralPath $sbom -PathType Leaf)) {
    throw "SBOM must be a generated file below the artifact root: $sbom"
}

$appDirectory = Join-Path $artifactRoot 'astock-terminal'
$portableZip = Join-Path $artifactRoot 'astock-terminal.zip'
$installer = Join-Path $artifactRoot 'astock-terminal-setup.exe'
$metadataPath = Join-Path $build.Paths.RendererDist 'build-metadata.json'
foreach ($required in @($appDirectory, $portableZip, $installer, $metadataPath)) {
    if (-not (Test-Path -LiteralPath $required)) { throw "Unsigned release input is missing: $required" }
}

$metadata = Get-Content -LiteralPath $metadataPath -Raw | ConvertFrom-Json
if ($metadata.application_version -ne '6.0.0' -or $metadata.platform -ne 'windows-x64' -or $metadata.commit -ne $commit) {
    throw 'Package build metadata is not bound to v6.0.0 and the expected commit.'
}

if (-not [string]::IsNullOrWhiteSpace($StageQualifier) -and $StageQualifier -notmatch '^[a-z0-9-]{1,32}$') {
    throw 'StageQualifier may contain only lowercase letters, digits, and hyphens.'
}
$stageName = "publish-unsigned-$($commit.Substring(0, 12))"
if (-not [string]::IsNullOrWhiteSpace($StageQualifier)) { $stageName += "-$StageQualifier" }
$publishStage = Join-Path $build.Paths.PackageStage $stageName
if (Test-Path -LiteralPath $publishStage) {
    $existing = @(Get-ChildItem -LiteralPath $publishStage -Force)
    if ($existing.Count -ne 0) { throw "Unsigned publish stage must be new and empty: $publishStage" }
} else {
    New-Item -ItemType Directory -Path $publishStage -Force | Out-Null
}

$releaseAssets = [ordered]@{
    'AStock-Terminal-v6.0.0-windows-x64.zip' = $portableZip
    'AStock-Terminal-v6.0.0-windows-x64-setup.exe' = $installer
    'AStock-Terminal-v6.0.0-build-metadata.json' = $metadataPath
    'AStock-Terminal-v6.0.0.cdx.json' = $sbom
    'AStock-Terminal-v6.0.0-migration.md' = (Join-Path $repository 'docs\releases\v6.0.0-migration.md')
}
foreach ($entry in $releaseAssets.GetEnumerator()) {
    if (-not (Test-Path -LiteralPath $entry.Value -PathType Leaf)) { throw "Release asset is missing: $($entry.Value)" }
    Copy-Item -LiteralPath $entry.Value -Destination (Join-Path $publishStage $entry.Key) -Force
}

$peFiles = @(
    Get-ChildItem -LiteralPath $appDirectory -Recurse -File |
        Where-Object Extension -in @('.exe', '.dll')
    Get-Item -LiteralPath $installer
)
if ($peFiles.Count -lt 4) { throw 'Packaged PE inventory is unexpectedly incomplete.' }
$peInventory = @($peFiles | Sort-Object FullName | ForEach-Object {
    $signature = Get-AuthenticodeSignature -LiteralPath $_.FullName
    [ordered]@{
        relative_path = if ($_.FullName -eq $installer) {
            'AStock-Terminal-v6.0.0-windows-x64-setup.exe'
        } else {
            'app/' + [System.IO.Path]::GetRelativePath($appDirectory, $_.FullName).Replace('\', '/')
        }
        sha256 = (Get-FileHash -Algorithm SHA256 -LiteralPath $_.FullName).Hash.ToLowerInvariant()
        authenticode_status = $signature.Status.ToString()
    }
})

$noticePath = Join-Path $publishStage 'AStock-Terminal-v6.0.0-UNSIGNED-NOTICE.txt'
$notice = @"
AStock Terminal v6.0.0 is distributed without project Authenticode signing.
Windows may display an Unknown Publisher or SmartScreen warning.

Integrity and origin are provided separately through SHA-256 manifests and
GitHub OIDC/Sigstore artifact attestations generated by the public repository's
GitHub-hosted release workflow. This is not an Authenticode signature.

Verify an asset with:
  gh attestation verify <asset> -R jacek4yang/astock-terminal

Source commit: $commit
"@
[System.IO.File]::WriteAllText($noticePath, $notice, [System.Text.UTF8Encoding]::new($false))

$verificationPath = Join-Path $publishStage 'AStock-Terminal-v6.0.0-verification.json'
$verification = [ordered]@{
    schema_version = 1
    application_version = '6.0.0'
    commit = $commit
    platform = 'windows-x64'
    distribution = [ordered]@{
        mode = 'github-oidc-attested-unsigned'
        authenticode = 'NOT PROVIDED'
        sha256_manifest = 'REQUIRED'
        github_artifact_attestation = 'GENERATED AFTER STAGING'
    }
    release_safety = [ordered]@{
        automatic_trading = $false
        credentials_embedded = $false
        human_review_required = $true
    }
    known_unverified = @(
        'Codex in-app browser 12-scenario acceptance',
        'packaged Proton/CEF 40-scenario desktop acceptance',
        'migration and performance acceptance on the tagged build',
        'live MiniMax Plus and JoinQuant credentialed provider flow'
    )
    pe_inventory = $peInventory
}
$verification | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $verificationPath -Encoding utf8NoBOM

$manifestPath = Join-Path $publishStage 'AStock-Terminal-v6.0.0-SHA256SUMS.txt'
$manifestLines = foreach ($file in Get-ChildItem -LiteralPath $publishStage -File | Sort-Object Name) {
    if ($file.FullName -eq $manifestPath) { continue }
    $hash = (Get-FileHash -Algorithm SHA256 -LiteralPath $file.FullName).Hash.ToLowerInvariant()
    "$hash  $($file.Name)"
}
[System.IO.File]::WriteAllLines($manifestPath, $manifestLines, [System.Text.UTF8Encoding]::new($false))

foreach ($line in Get-Content -LiteralPath $manifestPath) {
    if ($line -notmatch '^([a-f0-9]{64})  (.+)$') { throw "Invalid unsigned SHA256SUMS line: $line" }
    $target = Join-Path $publishStage $Matches[2]
    if (-not (Test-Path -LiteralPath $target -PathType Leaf)) { throw "Manifest target is missing: $target" }
    $actual = (Get-FileHash -Algorithm SHA256 -LiteralPath $target).Hash.ToLowerInvariant()
    if ($actual -ne $Matches[1]) { throw "Manifest target changed during staging: $target" }
}

if (-not [string]::IsNullOrWhiteSpace($env:GITHUB_OUTPUT)) {
    "publish_stage=$publishStage" | Out-File -LiteralPath $env:GITHUB_OUTPUT -Encoding utf8 -Append
}
Write-Host "Unsigned attested release stage: $publishStage"
