//! Unit tests for the minute-level pipeline (hand-built sequences) plus a
//! synthetic end-to-end test against a fixture generated by the legacy
//! Python engine (`tests/fixtures/minute_synthetic.json`).

mod common;

use astock_chanlun::minute::{
    analyze_chanlun_minute, construct_5min_klines, find_fractals, find_strokes, merge_klines,
    signals_to_dict, Fractal, MinuteKline,
};
use serde_json::Value;

/// Build a 5-minute kline where only high/low matter (open/close = mid).
fn mk(time: &str, high: f64, low: f64) -> MinuteKline {
    MinuteKline {
        time: time.to_string(),
        open: (high + low) / 2.0,
        close: (high + low) / 2.0,
        high,
        low,
        volume: 1.0,
    }
}

fn fractal(index: usize, fractal_type: &str, price: f64) -> Fractal {
    Fractal {
        index,
        fractal_type: fractal_type.to_string(),
        price,
        time: format!("t{index}"),
    }
}

fn times_range(start_h: u32, start_m: u32, count: u32) -> Vec<String> {
    let base = start_h * 60 + start_m;
    (0..count)
        .map(|i| {
            let m = base + i;
            format!("{:02}:{:02}", m / 60, m % 60)
        })
        .collect()
}

// ---------- construct_5min_klines ----------

#[test]
fn construct_groups_every_five_minutes() {
    let times = times_range(9, 30, 12);
    let prices: Vec<f64> = (1..=12).map(|x| x as f64).collect();
    let volumes: Vec<f64> = (0..12).map(|x| (x + 1) as f64 * 10.0).collect();
    let klines = construct_5min_klines(&times, &prices, &volumes);
    // Two full groups plus a trailing partial group of 2.
    assert_eq!(klines.len(), 3);
    // Klines are timestamped by the last minute of their group.
    assert_eq!(klines[0].time, "09:34");
    assert_eq!(klines[1].time, "09:39");
    assert_eq!(klines[2].time, "09:41");
    // OHLCV aggregation of the first group.
    assert_eq!(klines[0].open, 1.0);
    assert_eq!(klines[0].close, 5.0);
    assert_eq!(klines[0].high, 5.0);
    assert_eq!(klines[0].low, 1.0);
    assert_eq!(klines[0].volume, 10.0 + 20.0 + 30.0 + 40.0 + 50.0);
    // Trailing partial group.
    assert_eq!(klines[2].open, 11.0);
    assert_eq!(klines[2].close, 12.0);
}

#[test]
fn construct_resets_groups_at_session_break() {
    let mut times = times_range(11, 28, 3); // 11:28, 11:29, 11:30
    times.extend(times_range(13, 0, 6)); // afternoon session
    let prices: Vec<f64> = (1..=9).map(|x| x as f64).collect();
    let volumes = vec![1.0; 9];
    let klines = construct_5min_klines(&times, &prices, &volumes);
    // Morning partial group of 3, then 13:00..13:04 full group, then 13:05.
    assert_eq!(klines.len(), 3);
    assert_eq!(klines[0].time, "11:30");
    assert_eq!(klines[0].open, 1.0);
    assert_eq!(klines[0].close, 3.0);
    assert_eq!(klines[1].time, "13:04");
    assert_eq!(klines[1].open, 4.0);
    assert_eq!(klines[1].close, 8.0);
    assert_eq!(klines[2].time, "13:05");
    assert_eq!(klines[2].open, 9.0);
    assert_eq!(klines[2].close, 9.0);
}

#[test]
fn construct_empty_input() {
    let klines = construct_5min_klines(&[], &[], &[]);
    assert!(klines.is_empty());
}

// ---------- merge_klines ----------

#[test]
fn merge_up_direction_extends_max_max() {
    let klines = vec![mk("a", 10.0, 5.0), mk("b", 12.0, 6.0), mk("c", 11.5, 6.5)];
    let merged = merge_klines(&klines);
    assert_eq!(merged.len(), 2);
    assert_eq!(merged[0].direction, 0);
    assert_eq!(merged[1].direction, 1);
    // "c" is contained in "b"; up direction keeps max(high) and max(low).
    assert_eq!(merged[1].high, 12.0);
    assert_eq!(merged[1].low, 6.5);
    assert_eq!(merged[1].raw_count, 2);
    assert_eq!(merged[1].time_start, "b");
    assert_eq!(merged[1].time_end, "c");
}

#[test]
fn merge_down_direction_extends_min_min() {
    let klines = vec![mk("a", 10.0, 5.0), mk("b", 8.0, 4.0), mk("c", 7.5, 4.5)];
    let merged = merge_klines(&klines);
    assert_eq!(merged.len(), 2);
    assert_eq!(merged[1].direction, -1);
    // "c" is contained in "b"; down direction keeps min(high) and min(low).
    assert_eq!(merged[1].high, 7.5);
    assert_eq!(merged[1].low, 4.0);
    assert_eq!(merged[1].raw_count, 2);
}

#[test]
fn merge_undetermined_first_direction_extends_max_min() {
    // "b" contained in "a" while the segment direction is still 0:
    // high = max, low = min.
    let klines = vec![mk("a", 10.0, 5.0), mk("b", 9.0, 6.0)];
    let merged = merge_klines(&klines);
    assert_eq!(merged.len(), 1);
    assert_eq!(merged[0].direction, 0);
    assert_eq!(merged[0].high, 10.0);
    assert_eq!(merged[0].low, 5.0);
    assert_eq!(merged[0].raw_count, 2);
}

#[test]
fn merge_wrapping_kline_is_contained() {
    // "b" fully wraps "a" (higher high and lower low) -> containment branch.
    let klines = vec![mk("a", 10.0, 5.0), mk("b", 11.0, 4.0)];
    let merged = merge_klines(&klines);
    assert_eq!(merged.len(), 1);
    assert_eq!(merged[0].high, 11.0);
    assert_eq!(merged[0].low, 4.0);
}

#[test]
fn merge_single_kline() {
    let merged = merge_klines(&[mk("only", 3.0, 1.0)]);
    assert_eq!(merged.len(), 1);
    assert_eq!(merged[0].raw_count, 1);
}

// ---------- find_fractals ----------

#[test]
fn fractals_skip_boundary_klines() {
    let merged = merge_klines(&[
        mk("m0", 5.0, 1.0),
        mk("m1", 8.0, 2.0),   // top (high above both neighbours)
        mk("m2", 6.0, 1.5),   // bottom (low below both neighbours)
        mk("m3", 7.0, 1.6),   // top
        mk("m4", 6.5, 1.55),  // boundary: never a fractal
    ]);
    // Sanity: these are all mutually non-containing, so nothing merges.
    assert_eq!(merged.len(), 5);
    let fractals = find_fractals(&merged);
    assert_eq!(fractals.len(), 3);
    assert_eq!(fractals[0].index, 1);
    assert_eq!(fractals[0].fractal_type, "top");
    assert_eq!(fractals[0].price, 8.0);
    assert_eq!(fractals[0].time, "m1");
    assert_eq!(fractals[1].index, 2);
    assert_eq!(fractals[1].fractal_type, "bottom");
    assert_eq!(fractals[1].price, 1.5);
    assert_eq!(fractals[2].index, 3);
    assert_eq!(fractals[2].fractal_type, "top");
}

#[test]
fn fractal_doubly_qualified_kline_is_top() {
    // Middle kline has both the highest high and the lowest low; the legacy
    // if/elif classifies it as a top. Merged klines are constructed directly
    // (raw klines like these would be absorbed by the containment merge).
    let merged = vec![
        astock_chanlun::minute::MergedKline {
            time_start: "m0".into(),
            time_end: "m0".into(),
            high: 5.0,
            low: 4.0,
            direction: 1,
            raw_count: 1,
        },
        astock_chanlun::minute::MergedKline {
            time_start: "m1".into(),
            time_end: "m1".into(),
            high: 9.0,
            low: 3.0,
            direction: 1,
            raw_count: 1,
        },
        astock_chanlun::minute::MergedKline {
            time_start: "m2".into(),
            time_end: "m2".into(),
            high: 6.0,
            low: 4.5,
            direction: -1,
            raw_count: 1,
        },
    ];
    let fractals = find_fractals(&merged);
    assert_eq!(fractals.len(), 1);
    assert_eq!(fractals[0].fractal_type, "top");
    assert_eq!(fractals[0].price, 9.0);
}

// ---------- find_strokes ----------

#[test]
fn strokes_require_merged_index_gap_of_four() {
    let fractals = vec![
        fractal(0, "top", 10.0),    // start (down stroke)
        fractal(2, "bottom", 9.0),  // gap 2 < 4: ignored
        fractal(3, "bottom", 8.0),  // gap 3 < 4: ignored
        fractal(4, "bottom", 8.5),  // gap 4 >= 4: endpoint candidate
        fractal(6, "top", 11.0),    // same type as start with endpoint set -> close
        fractal(8, "top", 12.0),    // gap 8-4 = 4: endpoint of the up stroke
        fractal(9, "bottom", 7.0),  // same type as start (bottom) -> close
    ];
    let strokes = find_strokes(&fractals);
    assert_eq!(strokes.len(), 2);
    // First stroke: down, from fractal 0 to fractal 3.
    assert_eq!(strokes[0].direction, "down");
    assert_eq!(strokes[0].start_price, 10.0);
    assert_eq!(strokes[0].end_price, 8.5);
    assert_eq!(strokes[0].start_idx, 0);
    assert_eq!(strokes[0].end_idx, 3);
    // Second stroke: up, chained from fractal 3 to fractal 5.
    assert_eq!(strokes[1].direction, "up");
    assert_eq!(strokes[1].start_price, 8.5);
    assert_eq!(strokes[1].end_price, 12.0);
    assert_eq!(strokes[1].start_idx, 3);
    assert_eq!(strokes[1].end_idx, 5);
}

#[test]
fn strokes_move_start_to_more_extreme_same_type() {
    let fractals = vec![
        fractal(0, "top", 10.0),   // initial start
        fractal(2, "top", 11.0),   // more extreme top: start moves here
        fractal(3, "top", 10.5),   // less extreme: absorbed
        fractal(7, "bottom", 8.0), // gap 7-2 = 5: endpoint; final stroke emitted
    ];
    let strokes = find_strokes(&fractals);
    assert_eq!(strokes.len(), 1);
    assert_eq!(strokes[0].direction, "down");
    assert_eq!(strokes[0].start_price, 11.0);
    assert_eq!(strokes[0].start_idx, 1);
    assert_eq!(strokes[0].end_price, 8.0);
    assert_eq!(strokes[0].end_idx, 3);
}

#[test]
fn strokes_empty_fractals() {
    assert!(find_strokes(&[]).is_empty());
}

// ---------- end-to-end against the legacy-generated fixture ----------

#[test]
fn minute_synthetic_matches_legacy() {
    let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/minute_synthetic.json");
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
    let fixture: Value = serde_json::from_str(&raw).unwrap();

    let inputs = &fixture["inputs"];
    let times: Vec<String> = inputs["times"]
        .as_array()
        .unwrap()
        .iter()
        .map(|t| t.as_str().unwrap().to_string())
        .collect();
    let prices: Vec<f64> = inputs["prices"]
        .as_array()
        .unwrap()
        .iter()
        .map(|p| p.as_f64().unwrap())
        .collect();
    let volumes: Vec<f64> = inputs["volumes"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap())
        .collect();

    let result = analyze_chanlun_minute(&times, &prices, &volumes);
    let actual = signals_to_dict(&result);

    let mut errors = Vec::new();
    common::compare_values("minute", &fixture["expected"], &actual, &mut errors);
    assert!(errors.is_empty(), "minute mismatches:\n{}", errors.join("\n"));

    // The synthetic series produces 48 5-minute klines, 14 fractals,
    // 4 strokes and exactly one sell1 signal.
    assert_eq!(result.kline_count, 48);
    assert_eq!(result.stroke_count, 4);
    assert_eq!(result.signals.len(), 1);
    assert_eq!(result.signals[0].signal_type, "sell1");
}
